# Generated by Django 3.2.5 on 2022-08-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('flight_identifier', models.CharField(max_length=50)),
                ('flt_num', models.IntegerField()),
                ('scheduled_origin_gate', models.CharField(max_length=10)),
                ('scheduled_destination_gate', models.CharField(max_length=10)),
                ('out_gmt', models.DateTimeField()),
                ('in_gmt', models.DateTimeField()),
                ('off_gmt', models.DateTimeField()),
                ('on_gmt', models.DateTimeField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='flightmanager.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='flightmanager.airport')),
            ],
        ),
    ]
