# Generated by Django 3.2.5 on 2022-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmanager', '0002_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='abbv',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
